### ISSUE TITLE
Add <AdditionalInfo> to integration for campaignID

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-lowermybills#18]
Client and lead vendor has asked for the following:

Please allow the usage of the tag <AdditionalInformation>  to pass campaignID.

https://drive.google.com/drive/u/1/folders/0B36C7G4bQKsANVBIV0J3dVpHVWs

This is the primary place that the vendor has requested to dynamically adjust the campaignID based on lead scoring data. 

https://activeprospect.zendesk.com/agent/tickets/7029

**Comment by alexkwolfe** [comment]
We don't have a field to map this to.

**Comment by alexj** [comment]
Following up on conversations and emails from last week. We need to add the *Additional Information* field to the inbound integration, so that Karalyn can then use it within LeadConduit. The data passed within this field would not be available otherwise, but is critical for one of our clients.

Please let me know if there is anything else needed to proceed. Thanks! 

CC @poppop51
