### ISSUE TITLE
missing numeric values are set to "NaN"

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-lowermybills#25]
I've seen this for Loan Down Payment and Loan LTV, as below. There may be others; all numeric fields should be checked. 

![screen shot 2015-06-18 at 4 35 59 pm](https://cloud.githubusercontent.com/assets/5596/8242886/3c509964-15d8-11e5-90cb-23e8d48bbe85.png)

**Comment by cgrayson** [comment]
Fixed as of 1.2.1.

**Comment by alexkwolfe** [comment]
I think this is a big in the handler. Integration authors should be able to pass numbers that evaluate to NaN without it showing up as such in the UI. We don't want everyone to ghave to write and maintain checkNaN functions.

**Comment by alexkwolfe** [comment]
OK. This isn't a bug in the handler, but rather a bug in the number type. After parsing, the `raw` value is "NaN", and the `valid` property is `false`. The number type should be maintaining the raw value that was submitted.

![pastedgraphic-2](https://cloud.githubusercontent.com/assets/569/8245355/e2897a70-15f2-11e5-9c1d-df6534a05524.png)

**Comment by alexkwolfe** [comment]
Upon further inspection, the number type is operating correctly. I think the root cause is this integration, which is returning the evaluation of `parseInt()`. 

https://github.com/activeprospect/leadconduit-integration-lowermybills/blob/bdebe03b11453a452ca152cdd12cd7746bf7efc4/src/inbound.coffee#L63-L64

If the integration returned the raw string value (or null as the case may be), the number type will correctly handle it and the UI would show it correctly. I think there's also an argument to be made for the UI to show something special when the integration does return an actual NaN value.

**Comment by cgrayson** [comment]
As discussed offline, the further improvement here (and in other integrations with no submitted value for a field), is to not set the field at all. I.e., `mortgage.loan.down_payment` should not exist on the lead created by the integration.

/cc @jgrayson676
